// Objective-C API for talking to github.com/metacubex/mihomo Go package.
//   gobind -lang=objc github.com/metacubex/mihomo
//
// File is generated by gobind. Do not edit.

#ifndef __Mihomo_H__
#define __Mihomo_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class MihomoPlatformInterfaceBridge;
@protocol MihomoAppleNetworkinterface;
@class MihomoAppleNetworkinterface;
@protocol MihomoPlatformInterface;
@class MihomoPlatformInterface;
@protocol MihomoTunOptions;
@class MihomoTunOptions;

@protocol MihomoAppleNetworkinterface <NSObject>
- (long)writePacket:(NSData* _Nullable)payload;
@end

@protocol MihomoPlatformInterface <NSObject>
- (BOOL)openTun:(id<MihomoTunOptions> _Nullable)options ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (void)print:(NSString* _Nullable)log;
@end

@protocol MihomoTunOptions <NSObject>
- (BOOL)getAutoRoute;
- (NSString* _Nonnull)getIPv4Address;
- (NSString* _Nonnull)getIPv4Mask;
- (NSString* _Nonnull)getIPv6Address;
- (int32_t)getIPv6Prefix;
- (int32_t)getMTU;
- (BOOL)getStrictRoute;
@end

@interface MihomoPlatformInterfaceBridge : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
// skipped method PlatformInterfaceBridge.OpenTun with unsupported parameter or return types

@end

FOUNDATION_EXPORT int32_t MihomoGetTunnelFileDescriptor(void);

FOUNDATION_EXPORT NSString* _Nonnull MihomoGetVersion(void);

FOUNDATION_EXPORT void MihomoInitForceFree(int64_t maxMemory, long interval);

FOUNDATION_EXPORT int64_t MihomoQueryStatistics(NSString* _Nullable tag, NSString* _Nullable direct);

FOUNDATION_EXPORT void MihomoRegisterAppleNetworkInterface(id<MihomoAppleNetworkinterface> _Nullable packetFlow);

FOUNDATION_EXPORT NSString* _Nonnull MihomoStartVPN(id<MihomoPlatformInterface> _Nullable platform, NSString* _Nullable homeDir, NSString* _Nullable configString);

FOUNDATION_EXPORT void MihomoStopVPN(void);

FOUNDATION_EXPORT void MihomoWriteAppleNetworkInterfacePacket(NSData* _Nullable data);

@class MihomoAppleNetworkinterface;

@class MihomoPlatformInterface;

@class MihomoTunOptions;

@interface MihomoAppleNetworkinterface : NSObject <goSeqRefInterface, MihomoAppleNetworkinterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (long)writePacket:(NSData* _Nullable)payload;
@end

@interface MihomoPlatformInterface : NSObject <goSeqRefInterface, MihomoPlatformInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)openTun:(id<MihomoTunOptions> _Nullable)options ret0_:(int32_t* _Nullable)ret0_ error:(NSError* _Nullable* _Nullable)error;
- (void)print:(NSString* _Nullable)log;
@end

@interface MihomoTunOptions : NSObject <goSeqRefInterface, MihomoTunOptions> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (BOOL)getAutoRoute;
- (NSString* _Nonnull)getIPv4Address;
- (NSString* _Nonnull)getIPv4Mask;
- (NSString* _Nonnull)getIPv6Address;
- (int32_t)getIPv6Prefix;
- (int32_t)getMTU;
- (BOOL)getStrictRoute;
@end

#endif
