
// Objective-C API for talking to the following Go packages
//
//	github.com/metacubex/mihomo
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mihomo_FRAMEWORK_H__
#define __Mihomo_FRAMEWORK_H__

#include "Mihomo.objc.h"
#include "Universe.objc.h"

#endif
